export const START_FETCHING_PAYMENT_METHODS = "START_FETCHING_PAYMENT_METHODS";
export const SUCCESS_FETCHING_PAYMENT_METHODS =
  "SUCCESS_FETCHING_PAYMENT_METHODS";
export const FAIL_FETCHING_PAYMENT_METHODS = "SUCCESS_FETCHING_PAYMENT_METHODS";
export const SET_CURRENT_METHOD = "SET_CURRENT_METHOD";
